### ISSUE TITLE
TLS SNI connections to name-based VirtualHosts with TLSCertificateChainFile fail unexpectedly

### ISSUE THREAD

**Issue by rlaager** [proftpd/proftpd#1074]
This is a bit subtle. There could be as many as three different interacting issues here. On the plus side, this is all reproducible for me.

### What I Did

Connections to the second (or presumably subsequent) named-based virtual host fail the TLS negotiation. In the TLS log, I get:
```
2020-07-27 20:28:02,036 mod_tls/2.9[2196]: unable to accept TLS connection: protocol error: 
  (1) error:0909006C:PEM routines:get_name:no start line [Expecting: CERTIFICATE]
```

With the configuration provided below, `openssl s_client -connect coderich.net:21 -starttls ftp` fails, but `openssl s_client -connect bison.wiktel.com -starttls ftp` works. Likewise for implicit TLS with `openssl s_client -connect coderich.net:990` vs `openssl s_client -connect bison.wiktel.com:990`. If you flip the order of the `<VirtualHost>`s, the problem follows the order of them, not the names. That is, the first one always works, and the second one always fails.

Here is some more debug output from `proftpd -nXd10`:
```
2020-07-27 22:43:14,607 mod_tls/2.9[5007]: added 1 certs from '/etc/letsencrypt/live/coderich.net/chain.pem' to certificate chain
2020-07-27 22:43:14,607 bison proftpd[5007] bison.wiktel.com (HOSTNAME[IP]): mod_tls/2.9: supporting TLSv1, TLSv1.1, TLSv1.2, TLSv1.3 protocols
2020-07-27 22:43:14,608 bison proftpd[5007] bison.wiktel.com (HOSTNAME[IP]): mod_tls/2.9: supporting TLSv1, TLSv1.1, TLSv1.2, TLSv1.3 protocols
2020-07-27 22:43:14,612 mod_tls/2.9[5007]: unable to accept TLS connection: protocol error: 
  (1) error:0909006C:PEM routines:get_name:no start line [Expecting: CERTIFICATE]
2020-07-27 22:43:14,612 mod_tls/2.9[5007]: implicit SSL/TLS negotiation failed on control channel
2020-07-27 22:43:14,612 bison proftpd[5007] bison.wiktel.com (HOSTNAME[IP]): mod_tls.c: error initializing session: Permission denied
```

In other testing, I've noticed that there were two "added 1 certs from ... to certificate chain", one for bison.wiktel.com/chain.pem and one for coderich.net/chain.pem. That could be related, though maybe it doesn't always happen?

**If I comment out all the `TLSCertificateChainFile` lines from the configuration, then it works.** So clearly, the chain is a factor in some way.

Of course, then it doesn't serve the intermediate certificate. I tried adding `TLSCACertificatePath /etc/ssl/certs` to `<Global>` to see if that would fix it. It didn't. But I realized that is because the Let's Encrypt intermediate isn't in the list of root CA certificates. If I create a directory with just the intermediate and reference that, then everything works!

**To recap, that working state is the minimal configuration from below, minus all the `TLSCertificateChainFile` lines, plus a `<Global>` `TLSCACertificatePath /etc/letsencrypt/proftpd` with that directory containing the [Let's Encrypt intermediate certificate](https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt) as a file named `4f06f81d.0`.**

**If I then re-add `LoadModule mod_quotatab.c` (from the default modules.conf) after `LoadModule mod_tls.c`, it breaks again in the same way. If I swap the order of the modules so mod_quotatab is before mod_tls, it works.**

### What I Expected/Wanted

I have a shared-hosting server (in this case bison.wiktel.com). I want to support FTPS with SNI. When a user connects with either explicit or implicit TLS and uses SNI, I want them to get the certificate (and chain) corresponding to the name the user requested. At this time, all other behavior (logins, directories, etc.) would still be the same regardless of the name they use.

### ProFTPD Version and Configuration

Because I need the SNI name-based virtual host support, I rebuilt the proftpd 1.3.7a package from Debian unstable on Ubuntu 18.04:
```
Compile-time Settings:
  Version: 1.3.7a (maint)
  Platform: LINUX [Linux 4.15.0-96-generic x86_64]
  Built: Mon Jul 27 2020 06:19:54 UTC
  Built With:
    configure  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--disable-strip' '--enable-redis' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession:mod_auth_otp:mod_tls_redis:mod_wrap2_redis:mod_redis:mod_memcache:mod_tls_memcache:mod_readme:mod_snmp:mod_digest:mod_ident:mod_log_forensic:mod_qos:mod_statcache:mod_tls_fscache:mod_tls_shmcache' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-Hg9AQ9/proftpd-dfsg-1.3.7a=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-Hg9AQ9/proftpd-dfsg-1.3.7a=. -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g2 -g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-Hg9AQ9/proftpd-dfsg-1.3.7a=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lsodium -lcap  -lpam -lsupp -lattr -lnsl -lresolv -lresolv -lcrypt -ldl -lhiredis -lmemcachedutil -lmemcached  -pthread

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncurses support
    + NLS support
    + OpenSSL support (OpenSSL 1.1.1  11 Sep 2018)
    + PCRE support
    + POSIX ACL support
    + Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

Here is a relatively minimal proftpd.conf that reproduces the problem:
```
ModulePath /usr/lib/proftpd
LoadModule mod_tls.c

<Global>
    TLSEngine on
    TLSLog /var/log/proftpd/tls.log
    User proftpd
    Group nogroup
</Global>

DefaultAddress 127.0.0.1 ::1
TLSRSACertificateKeyFile /etc/letsencrypt/live/bison.wiktel.com/privkey.pem
TLSCertificateChainFile /etc/letsencrypt/live/bison.wiktel.com/chain.pem
TLSRSACertificateFile /etc/letsencrypt/live/bison.wiktel.com/cert.pem

<VirtualHost 69.89.207.26 2600:2600::26>
    ServerAlias bison.wiktel.com
    TLSRSACertificateKeyFile /etc/letsencrypt/live/bison.wiktel.com/privkey.pem
    TLSCertificateChainFile /etc/letsencrypt/live/bison.wiktel.com/chain.pem
    TLSRSACertificateFile /etc/letsencrypt/live/bison.wiktel.com/cert.pem
</VirtualHost>
<VirtualHost 69.89.207.26 2600:2600::26>
    ServerAlias bison.wiktel.com
    Port 990
    TLSOptions NoSessionReuseRequired UseImplicitSSL
    TLSRSACertificateKeyFile /etc/letsencrypt/live/bison.wiktel.com/privkey.pem
    TLSCertificateChainFile /etc/letsencrypt/live/bison.wiktel.com/chain.pem
    TLSRSACertificateFile /etc/letsencrypt/live/bison.wiktel.com/cert.pem
</VirtualHost>

<VirtualHost 69.89.207.26 2600:2600::26>
    ServerAlias coderich.net www.coderich.net
    TLSRSACertificateKeyFile /etc/letsencrypt/live/coderich.net/privkey.pem
    TLSCertificateChainFile /etc/letsencrypt/live/coderich.net/chain.pem
    TLSRSACertificateFile /etc/letsencrypt/live/coderich.net/cert.pem
</VirtualHost>
<VirtualHost 69.89.207.26 2600:2600::26>
    ServerAlias coderich.net www.coderich.net
    Port 990
    TLSOptions NoSessionReuseRequired UseImplicitSSL
    TLSRSACertificateKeyFile /etc/letsencrypt/live/coderich.net/privkey.pem
    TLSCertificateChainFile /etc/letsencrypt/live/coderich.net/chain.pem
    TLSRSACertificateFile /etc/letsencrypt/live/coderich.net/cert.pem
</VirtualHost>
```

----

The following is almost a separate issue:

I fought with the configuration quite a bit. The "server config" host gave me a lot of trouble, so
as you can see, I ultimately neutered that by setting `DefaultAddress 127.0.0.1 ::1` so it only listens on localhost. That may or may not be a permanent configuration, but at least it means that all the interesting stuff is in `<VirtualHost>`s.

In my case, bison.wiktel.com resolves to 69.89.207.26 and 2600:2600::26. I put both of those in `/etc/hosts`. I tried to remove the `DefaultAddress` hack like this:

```
--- proftpd.test.conf	2020-07-28 00:17:24.748882843 -0500
+++ proftpd.test2.conf	2020-07-28 00:24:14.935680330 -0500
@@ -9,19 +9,13 @@
     TLSCACertificatePath /etc/letsencrypt/proftpd
 </Global>
 
-DefaultAddress 127.0.0.1 ::1
+ServerAlias bison.wiktel.com
 TLSRSACertificateKeyFile /etc/letsencrypt/live/bison.wiktel.com/privkey.pem
 #TLSCertificateChainFile /etc/letsencrypt/live/bison.wiktel.com/chain.pem
 TLSRSACertificateFile /etc/letsencrypt/live/bison.wiktel.com/cert.pem
 
 <VirtualHost 69.89.207.26 2600:2600::26>
     ServerAlias bison.wiktel.com
-    TLSRSACertificateKeyFile /etc/letsencrypt/live/bison.wiktel.com/privkey.pem
-#    TLSCertificateChainFile /etc/letsencrypt/live/bison.wiktel.com/chain.pem
-    TLSRSACertificateFile /etc/letsencrypt/live/bison.wiktel.com/cert.pem
-</VirtualHost>
-<VirtualHost 69.89.207.26 2600:2600::26>
-    ServerAlias bison.wiktel.com
     Port 990
     TLSOptions NoSessionReuseRequired UseImplicitSSL
     TLSRSACertificateKeyFile /etc/letsencrypt/live/bison.wiktel.com/privkey.pem
```

My thinking is that the "server config" host should now be the same as that first `<VirtualHost>` that I removed. Unfortunately, `openssl s_client -connect bison.wiktel.com:21 -starttls ftp` (and only that one; bison.wiktel.com:990 and both the coderich.net ports are fine) fails the TLS handshake. I get this output:
```
2020-07-28 00:27:22,412 bison proftpd[29011] bison.wiktel.com (HOSTNAME[IP]): mod_tls/2.9: no matching server found for client-sent SNI 'bison.wiktel.com', rejecting SSL/TLS connection
```

**Comment by rlaager** [comment]
I found another issue. Mixing `<VirtualHost 69.89.207.26 2600:2600::26>` and `<VirtualHost 2600:2600::26 69.89.207.26>` breaks things. For example, using the former (IPv4 first) for bison and the latter (IPv6 first) for coderich.net, in that order, means that coderich.net is broken.

**Comment by jb-boin** [comment]
I am also testing the SNI support and with the default configuration (from the Debian packaging) with mod_quotatab loaded (but not used in my case) the server was crashing when i was trying to connect using TLS :
> -----BEGIN STACK TRACE-----
> [0] /usr/lib/proftpd/mod_quotatab.so(+0x6521) [0x7f45c1d97521]
> [1] /usr/lib/proftpd/mod_quotatab.so(+0x6521) [0x7f45c1d97521]
> [2] proftpd: 1.2.3.4:49208: AUTH TLS(pr_event_generate+0x130) [0x55d190be3010]
> [3] /usr/lib/proftpd/mod_tls.so(+0x1528a) [0x7f45c27dc28a]
> [4] proftpd: 1.2.3.4:49208: AUTH TLS(pr_module_call+0x44) [0x55d190bcd644]
> [5] proftpd: 1.2.3.4:49208: AUTH TLS(+0x1e2a2) [0x55d190ba12a2]
> [6] proftpd: 1.2.3.4:49208: AUTH TLS(pr_cmd_dispatch_phase+0x5d0) [0x55d190ba3fc0]
> [7] proftpd: 1.2.3.4:49208: AUTH TLS(+0x2108d) [0x55d190ba408d]
> [8] proftpd: 1.2.3.4:49208: AUTH TLS(+0x1f1ee) [0x55d190ba21ee]
> [9] proftpd: 1.2.3.4:49208: AUTH TLS(+0x1faf6) [0x55d190ba2af6]
> [10] proftpd: 1.2.3.4:49208: AUTH TLS(main+0x593) [0x55d190ba0a23]
> [11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f45c2ea609b]
> [12] proftpd: 1.2.3.4:49208: AUTH TLS(_start+0x2a) [0x55d190ba0f8a]
> -----END STACK TRACE-----
> ProFTPD terminating (signal 11)

I commented the loading of the quotatab module and have not had this issue again.

--

Another note that might be of interest to you is that i was trying to allow connections to the server from VHosts that are not listed on the the server configuration by using `DefaultServer On` on one of the VHost without any success, i also tried to load a certificate outside of a  `<VirtualHost>` directive but in both case, i was having the `mod_tls/2.9: no matching server found for client-sent SNI 'test.vhost', rejecting SSL/TLS connection` error.

The solution to this is to put `ServerAlias *` on the VHost you want as the default one.

**Comment by rlaager** [comment]
This isn't directly applicable to this server-side bug, but if anyone is looking for actual FTP clients (other than `openssl s_client` to test with:
- WinSCP is adding SNI support. The developer privately sent me a test version. SNI works for FTPS explicit, but not (yet) for FTPs implicit. The public conversation is here: https://winscp.net/forum/viewtopic.php?t=27515#101155
- FileZilla supports SNI, but it doesn't do certificate verification under any circumstances. :(
- I requested SNI support from CyberDuck (by reopening an old bug): https://trac.cyberduck.io/ticket/9257#comment:2

**Comment by Castaglia** [comment]
I've also used `curl`, which does use SNI and support FTPS, for some of my testing/development.

**Comment by Castaglia** [comment]
I'm working on reproducing these reported behaviors now.

**Comment by Castaglia** [comment]
@rlaager In your OpenSSL commands, what happens if you use the `-servername` flag?  I.e.:
```
$ openssl s_client -connect coderich.net:21 -servername coderich.net -starttls ftp
$ openssl s_client -connect bison.wiktel.com -servername bison.wiktel.com -starttls ftp
$ openssl s_client -connect coderich.net:990 -servername coderich.net
$ openssl s_client -connect bison.wiktel.com:990 -servername bison.wiktel.com
```
Instead of:
```
$ openssl s_client -connect coderich.net:21 -starttls ftp
$ openssl s_client -connect bison.wiktel.com -starttls ftp
$ openssl s_client -connect coderich.net:990
$ openssl s_client -connect bison.wiktel.com:990
```

By default, `openssl s_client` does _not_ send SNI, since it does not automatically assume (unlike other clients) that the given DNS name (or IP address) is to be automatically used as the SNI.  So you often need to explicitly tell OpenSSL what SNI to use.

And without an SNI, when `mod_tls` receives the ClientHello, it will default to using whichever configuration has the [`DefaultServer`](http://www.proftpd.org/docs/modules/mod_core.html#DefaultServer) setting (if any), otherwise it uses the configuration that matches the IP address/port used for the client -- first matching vhost config wins, if there are multiple `<VirtualHost>` sections that match the IP address/port.

**Comment by rlaager** [comment]
I retested with the example config I gave here. There is no difference between those commands. On my system (Ubuntu 18.04), `openssl s_client` absolutely _is_ using SNI even without `-servername`. I can verify that in the effects (i.e. I get a coderich.net certificate whereas without SNI I would get bison.wiktel.com). But conclusively, I can see the `server_name` extension in a packet capture with Wireshark.

To recap, there are three issues:
1. When using `TLSCertificateChainFile`, the TLS negotiations fail. This can be worked around using `TLSCACertificatePath` with a directory containing the intermediate certificate named with a hash as per `openssl rehash`.
2. `LoadModule mod_quotatab.c` after (but not before) `LoadModule mod_tls.c` breaks things in the same way. This can be worked around by not loading `mod_quotatab` (or loading it first, but I wasn't using it anyway).
3. Mixing `<VirtualHost 69.89.207.26 2600:2600::26>` and `<VirtualHost 2600:2600::26 69.89.207.26>` breaks things. This can be worked around by always listing the IPs in the same order. I think, but did not extensively test, that having overlapping but non-identical sets of IPs can lead to similar issues (e.g. `<VirtualHost 69.89.207.26 2600:2600::26>` and `<VirtualHost 2600:2600::26>` or `<VirtualHost 69.89.207.26>`).

**Comment by Castaglia** [comment]
OK.  I'll tackle these issues one at a time.

First, I'm now able to reproduce the reported behavior when `TLSCertificateChainFile` is used.  The issue occurs only if SNI is used; it is _not_ specific to TLSv1.3, but occurs for older protocol versions as well.  _And_ it only happens for the second (and subsequent) named hosts for a given IP address/port; it does _not_ occur, even if SNI is used, if the named host is the first one defined for that IP address port.

Based on these criteria, I'll see what I can do to correct the issue.  Then we'll move on to the others.

**Comment by Castaglia** [comment]
For my future reference, the `TLSCertificateChainFile` issue, when it occurs, manifests like so in the logs:
```
2020-08-16 15:43:25,624 [9676] <tls:17>: SSL_accept() returned -1 for ctrl conn fd 0
2020-08-16 15:43:25,624 mod_tls/2.9[9676]: unable to accept TLS connection: protocol error: 
  (1) error:0909006C:PEM routines:get_name:no start line [Expecting: CERTIFICATE]
  (2) error:0909006C:PEM routines:get_name:no start line [Expecting: CERTIFICATE]
2020-08-16 15:43:25,624 [9676] <tls:17>: shutting down TLS session, 'close_notify' not already sent; sending now
2020-08-16 15:43:25,624 mod_tls/2.9[9676]: TLS/TLS-C negotiation failed on control channel
```
And, on the client side (using `openssl s_client`):
```
# openssl s_client -connect 127.0.0.1:2121 -starttls ftp -crlf -servername bar.castaglia.org
CONNECTED(00000005)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
```

**Comment by Castaglia** [comment]
@rlaager when you get a chance, could you try https://github.com/proftpd/proftpd/pull/1091?  I suspect that symptom #3 may also be fixed with that PR as well, on the assumption that changing/mixing the order of IP addresses changes the ordering of the virtual host definitions, which is one of the criteria observed for symptom #1.

**Comment by Castaglia** [comment]
Fix has been merged to master, and backported to the 1.3.7 branch.  Thanks!

**Comment by rlaager** [comment]
I have confirmed that the first issue was fixed in `master`. Thanks! I have opened #1105 for the next.

**Comment by rlaager** [comment]
I confirmed the backport in the 1.3.7 branch is good.

I re-tested the mod_quotatab issue, confirmed that is still a problem, retested that again on master, simplified the test case, and opened #1106 for that one. @jb-boin, you may want to follow #1106

**Comment by jb-boin** [comment]
Thanks, looks like everything has been fixed, will give it a try when i will have time to work on that :)
