### ISSUE TITLE
mod_quotatab_sql failing due to SQL syntax errors

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1149]
There is a regression in the [`mod_quotatab_sql`](http://www.proftpd.org/docs/contrib/mod_quotatab_sql.html) module in ProFTPD 1.3.7 (and later).  When `mod_quotatab_sql` is configured to _e.g._ insert into a tallies table, per its documentation:
```
SQLNamedQuery insert-quota-tally INSERT "%{0}, %{1}, %{2}, %{3}, %{4}, %{5}, %{6}, %{7}" quotatallies
```
and when a user, with no existing tallies entry, logs in, the login fails.  In a configured `SQLLogFile`, we see:
```
2020-11-03 06:13:37,360 mod_sql/4.5[98055]: >>> process_named_query 'insert-quota-tally'
...
2020-11-03 06:13:37,363 mod_sql/4.5[98055]: query "INSERT INTO quotatallies VALUES (''proftpd'', ''user'', 0.000000, 0.000000, 0.000000, 0, 0, 0)"
2020-11-03 06:13:37,363 mod_sql/4.5[98055]: error executing 'INSERT INTO quotatallies VALUES (''proftpd'', ''user'', 0.000000, 0.000000, 0.000000, 0, 0, 0)': (1) near "proftpd": syntax error
```
The above error comes from SQLite, but the same regression occurs using MySQL or Postgres as well.

As we can see, the issue is the extra single quotes that are somehow being added for the `%{0}`, `%{1}` values.

Interestingly, in the `SQLLogFile`, _before_ the custom `INSERT` statement, we see the `SELECT` from:
```
SQLNamedQuery get-quota-limit SELECT "name, quota_type, per_session, limit_type, bytes_in_avail, bytes_out_avail, bytes_xfer_avail, files_in_avail, files_out_avail, files_xfer_avail FROM quotalimits WHERE name = '%{0}' AND quota_type = '%{1}'"
```
and it appears to work as expected:
```
2020-11-03 06:13:37,356 mod_sql/4.5[98055]: >>> process_named_query 'get-quota-limit'
...
2020-11-03 06:13:37,357 mod_sql/4.5[98055]: query "SELECT name, quota_type, per_session, limit_type, bytes_in_avail, bytes_out_avail, bytes_xfer_avail, files_in_avail, files_out_avail, files_xfer_avail FROM quotalimits WHERE name = 'proftpd' AND quota_type = 'user'"
```
Why would `%{0}` and `%{1}` resolve properly the first time, but not a second/subsequent time?

**Comment by Castaglia** [comment]
I've found where the regression started: https://github.com/proftpd/proftpd/commit/5c22eb3b1b25bbea93a7c5e5e571bb20a4e6a05f, part of the refactoring of handing of `LogFormat` variables into a single Jot API, used across all modules.

This commit introduced an _additional_ call to "escape this text" to the backend SQL modules.  Prior to this additional "sql_escapestring" call, the `mod_quotatab_sql` module was hardcoded to add single quotes around the username, quota type text, to ensure that those strings were quoted.  But now, those strings are being quoted _twice_, hence the bug/regression.

**Comment by Castaglia** [comment]
This has now been fixed in master, and backported to the 1.3.7 branch.

**Comment by dddns** [comment]
Hi,
This still happens to me in latest GIT from today.
Maybe it's a place where this wasn't fixed already?
Thanks in advanced,

It's adding the escape into this query:

SQLNamedQuery insert-quota-tally INSERT "%{0}, %{1}, %{2}, %{3}, %{4}, %{5}, %{6}, %{7}" quotatallies


2020-12-27 16:22:07,443 mod_sql/4.5[41245]: query "INSERT INTO quotatallies VALUES (\'domain.pt\', \'user\', 0.000000, 0.000000, 0.000000, 0, 0, 0)"
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: entering    mysql cmd_close
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: connection 'default' count is now 1
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: exiting     mysql cmd_close
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: exiting     mysql cmd_insert
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: <<< process_named_query 'insert-quota-tally'
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: unrecoverable backend error
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: error: '1064'
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: message: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'domain.pt\', \'user\', 0.000000, 0.000000, 0.000000, 0, 0, 0)' at line 1'
2020-12-27 16:22:07,443 mod_sql/4.5[41245]: >>> cmd_endpwent

**Comment by dddns** [comment]
Oh, I'm so sorry for writing this, I forgot to make install it :/

It's perfect! Running 1.3.8RC1.
