### ISSUE TITLE
Can't register on the forum - cert expired & empty verification.

### ISSUE THREAD

**Issue by the7erm** [proftpd/proftpd#1163]
The cert has expired on the forum.  - Certbot isn't doing it's job?
![image](https://user-images.githubusercontent.com/2530157/101318677-f163f900-381d-11eb-86c1-f393036eff17.png)

The registration page has an empty verification section.  I'm guessing supposed to be captcha.
![image](https://user-images.githubusercontent.com/2530157/101318757-13f61200-381e-11eb-9512-daa9a47e7a73.png)

**Comment by bdacus01** [comment]
Still down.  Chrome throws a big Unsafe go back message.  Wish this was fixed.
Your connection is not fully secure
This site uses an outdated security configuration, which may expose your information (for example, passwords, messages, or credit cards) when it is sent to this site.
NET::ERR_SSL_OBSOLETE_VERSION

**Comment by mdell-seradex** [comment]
It is still not working and it throws a captcha error "The letters you typed don't match the letters that were shown in the picture" even though it never prompted for this.
It appears that the captcha links used by the forum are no longer valid because they give me a 404 error when trying to access them directly.

**Comment by mdell-seradex** [comment]
Looking at this a little further, based on the link used, it appears to be using google reCAPTCHA v1 which "has been shut down since March 2018" and "has been deprecated since May of 2016"
Google now offers reCAPTCHA v2 and reCAPTCHA v3.

**Comment by mdell-seradex** [comment]
Is there a contact that we should reach out to regarding this?
I have looked over the forums, scanned the proftpd.org site, and did some googling to try to find an appropriate contact but am unsure who it should be.

**Comment by Castaglia** [comment]
The short version is there's only one person (me) trying to manage everything for this project.  And I simply have not had enough free time/energy -- outside of my day job -- to look into this.

**Comment by mdell-seradex** [comment]
I was wondering about that.
It is unfortunate that you do not have others assisting with this project at this time. 😢 
That said, I think you are doing an excellent job. 😃 

Mark

**Comment by Castaglia** [comment]
I've just tried enabling a different kind of verification on the forums site; care to try again?

**Comment by mdell-seradex** [comment]
I definitely see the verification on the forums now.
For some reason though, the password text boxes are not detected by my browser so it cannot auto generate a password.
Could it be because it gives me this warning?
```
Your connection is not fully secure
This site uses an outdated security configuration, which may expose your information (for example, passwords, messages or credit cards) when it is sent to this site.
NET::ERR_SSL_OBSOLETE_VERSION
The connection used to load this site is TLS 1.0 or TLS 1.1, which are outdated and will be turned off in the future. When these are turned off, you won't be able to load the site. The server should use TLS 1.2 or later.
```

**Comment by Castaglia** [comment]
Possibly.  I don't know about browser idiosyncracies, so can't speak to why/why not they do/don't work.  I do know that trying to update to a new TLS protocol version involves _far more work_ that you might expect, for these installations.

**Comment by mdell-seradex** [comment]
Note that I have tried a couple of Chromium based browsers and they both have this behaviour.
I'd guess that the ease of updating to a new TLS protocol would depend on where/how the site is hosted.
According to the following, they had started deprecating it in Chrome 72 and had planned to completely deprecate support for those versions in Chrome 81.  https://www.chromestatus.com/feature/5654791610957824
It is likely that the pandemic has delayed this like it has delayed so many other things.

**Comment by mdell-seradex** [comment]
I also found this which says that a new certificate would not be required.
https://developers.google.com/web/updates/2020/05/chrome-84-deps-rems#remove_tls_10_and_tls_11
