### ISSUE TITLE
Site-to-site transfers over TLS fail

### ISSUE THREAD

**Issue by xvkdev** [proftpd/proftpd#618]
### What I Did

Attempted to do a site to site transfer with TLS required in the server and of course enabled on the client.

TLS log show a few worrying lines:

2017-10-29 14:32:17,103 mod_tls/2.8[21711]: TLSv1 connection accepted, using cipher DHE-RSA-AES256-SHA (256 bits)
2017-10-29 14:32:18,089 mod_tls/2.8[21711]: Protection set to Private
2017-10-29 14:32:18,437 mod_tls/2.8[21711]: starting TLS negotiation on data connection
2017-10-29 14:32:18,778 mod_tls/2.8[21711]: TLSv1 data connection accepted, using cipher DHE-RSA-AES256-SHA (256 bits)
2017-10-29 14:32:41,867 mod_tls/2.8[21711]: starting TLS negotiation on data connection
**2017-10-29 14:32:42,214 mod_tls/2.8[21711]: unable to accept TLS connection: system call error: [0] Success**
2017-10-29 14:32:42,214 mod_tls/2.8[21711]: unable to open data connection: TLS negotiation failed
2017-10-29 14:32:42,671 mod_tls/2.8[21944]: TLS/TLS-C requested, starting TLS handshake
2017-10-29 14:32:43,018 mod_tls/2.8[21944]: TLSv1 connection accepted, using cipher DHE-RSA-AES256-SHA (256 bits)
2017-10-29 14:32:44,483 mod_tls/2.8[21944]: Protection set to Private
2017-10-29 14:32:45,359 mod_tls/2.8[21944]: making TLS connection for data connection
**2017-10-29 14:32:45,360 mod_tls/2.8[21944]: unable to connect using TLS connection: protocol error:
  (1) error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
2017-10-29 14:32:45,360 mod_tls/2.8[21944]: unable to open data connection: TLS connection failed
2**

### What I Expected/Wanted

A successful transfer.

### ProFTPD Version and Configuration

Two ProFTPd involved: 1.3.5a and 1.3.7rc1 from git. The log above is from 1.3.7rc1.

TLS config:
```
    TLSEngine on

    TLSLog /var/log/tls_proftpd.log
    TLSRequired on
    TLSVerifyServer NoReverseDNS

    # Server's certificate
    TLSRSACertificateFile (path)
    TLSRSACertificateKeyFile (path)
    TLSCertificateChainFile (path)

    TLSVerifyClient off
    TLSOptions NoSessionReuseRequired

    TLSRenegotiate required off
```

**Comment by Castaglia** [comment]
Could you provide the [proftpd debug logging](http://www.proftpd.org/docs/howto/Debugging.html), debug level 10, as well please?  This will show the FTP commands used by the client...

**Comment by Castaglia** [comment]
Also, what version of OpenSSL are you using?  What does `openssl version -a` show?

**Comment by xvkdev** [comment]
OpenSSL 1.1.0f  25 May 2017
built on: reproducible build, date unspecified
platform: debian-amd64
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS
-DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2
-DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m
-DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM
-DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM
-DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\""
-DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\""
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
r

**Comment by Castaglia** [comment]
I had originally thought that this might be caused by the use of OpenSSL-1.1.x, whose APIs have changed.  However, I was able to reproduce the behavior using OpenSSL-1.0.x.  [This PR](https://github.com/proftpd/proftpd/pull/628) should address the issue.

**Comment by Castaglia** [comment]
Fixed in master, and backported to the 1.3.6 branch.  Thanks!

**Comment by pimseb** [comment]
is it already fixed in 1.3.5b-4 ? I'm using it under Raspbian Stretch and think got this error aswell

**Comment by Castaglia** [comment]
@pimseb No, this fix was only backported to the 1.3.6 branch.  The 1.3.5 series is no longer maintained/supported; see the [Versioning](http://www.proftpd.org/docs/howto/Versioning.html) howto.

**Comment by alitteration** [comment]
Hello, I still experience that same issue and when trying to install proftpd in ubuntu 18.04, I get 1.3.5, any way to fix this on the current 1.3.5 ?

**Comment by stephen-hill** [comment]
I'm currently experiencing this issue on FreeBSD 12.3, proftpd version 1.3.7c.

**Comment by stephen-hill** [comment]
For me, I resolved the issue on the server by adding the following config.

```
<IfModule mod_tls.c>
...
TLSOptions NoSessionReuseRequired
...
</IfModule>```
